version: 1.12.0.{build}
branches:
    only:
        - master
skip_tags: true
clone_folder: C:\Cube\Cube.Net
image: Visual Studio 2017
nuget:
    project_feed: true
    disable_publish_on_pr: true
platform: Any CPU
configuration: Release
before_build:
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget sources add -name Cube.FileSystem -source https://ci.appveyor.com/nuget/cube.filesystem
    - nuget sources add -name Cube.Images -source https://ci.appveyor.com/nuget/cube.images
    - nuget sources add -name Cube.Forms -source https://ci.appveyor.com/nuget/cube.forms
    - nuget sources add -name Cube.Xui -source https://ci.appveyor.com/nuget/cube.xui
    - nuget restore Cube.Net.Rss.sln
build:
    parallel: true
    project: Cube.Net.Rss.sln
    publish_nuget: true
    verbosity: minimal
test_script:
    - >
      ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe
      -log:Error
      -register:user
      -target:nunit3-console.exe
      -targetargs:Cube.Net.Tests.dll
      -targetdir:Tests\bin\Release
      -returntargetcode
      -hideskipped:All
      -output:CoverResults.xml
      -filter:"+[Cube*]* -[*]*NativeMethods -[*]*Properties.*"
    - >
      ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe
      -log:Error
      -register:user
      -target:nunit3-console.exe
      -targetargs:"Cube.Net.Rss.Tests.dll --workers=1"
      -targetdir:Applications\Rss\Tests\bin\Release
      -returntargetcode
      -hideskipped:All
      -mergeoutput
      -output:CoverResults.xml
      -filter:"+[Cube*]* -[*]*NativeMethods -[*]*Properties.* -[*]*Window -[*]*Control -[*]*.App"
after_test:
    - xcopy /q /Y /I Applications\Rss\Reader\bin\Release CubeRssReader
    - xcopy /q /Y /I Tests\bin\Release\Cube.Net.Tests.log Tests\
    - xcopy /q /Y /I Applications\Rss\Tests\bin\Release\Cube.Net.Rss.Tests.log Tests\
    - xcopy /q /Y /I CoverResults.xml Tests\
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f CoverResults.xml
artifacts:
    - path: CubeRssReader
    - path: Tests
